version: '3'

services:
    db:
        image: "postgres:13-alpine"
        env_file:
            - db.env
        volumes:
            - ./db_data/:/var/lib/postgresql/data/
        networks:
            - notes_network

    backend:
        build: ./backend/.
        env_file:
            - api.env
        command: uvicorn main:app --host backend --port 80
        depends_on:
            - db
        networks:
            - notes_network
        ports:
            - 5050:80
    
    frontend:
        build: ./frontend/.
        volumes:
            - ./frontend/templates/:/usr/share/nginx/html
        depends_on:
            - db
            - backend
        networks:
            - notes_network
        ports:
            - 8080:80

networks:
    notes_network:
        driver: bridge
